# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mdi_testy.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(854, 635)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Main_layout = QtWidgets.QGridLayout()
        self.Main_layout.setObjectName("Main_layout")
        self.Main_buttons_layout = QtWidgets.QHBoxLayout()
        self.Main_buttons_layout.setObjectName("Main_buttons_layout")
        self.Status_button = QtWidgets.QPushButton(Form)
        self.Status_button.setMinimumSize(QtCore.QSize(0, 50))
        self.Status_button.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"    background-color: rgb(94, 92, 100);\n"
"    background-color: rgb(119, 118, 123);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.Status_button.setObjectName("Status_button")
        self.Main_buttons_layout.addWidget(self.Status_button)
        self.Recent_button = QtWidgets.QPushButton(Form)
        self.Recent_button.setMinimumSize(QtCore.QSize(0, 50))
        self.Recent_button.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.Recent_button.setObjectName("Recent_button")
        self.Main_buttons_layout.addWidget(self.Recent_button)
        self.Contacts_button = QtWidgets.QPushButton(Form)
        self.Contacts_button.setMinimumSize(QtCore.QSize(0, 50))
        self.Contacts_button.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.Contacts_button.setObjectName("Contacts_button")
        self.Main_buttons_layout.addWidget(self.Contacts_button)
        self.Main_layout.addLayout(self.Main_buttons_layout, 7, 0, 1, 1)
        self.Lists_2_layout = QtWidgets.QHBoxLayout()
        self.Lists_2_layout.setContentsMargins(-1, 0, -1, -1)
        self.Lists_2_layout.setObjectName("Lists_2_layout")
        self.Main_layout.addLayout(self.Lists_2_layout, 2, 0, 1, 1)
        self.Keyboard_layout = QtWidgets.QGridLayout()
        self.Keyboard_layout.setContentsMargins(-1, 0, -1, -1)
        self.Keyboard_layout.setObjectName("Keyboard_layout")
        self.b = QtWidgets.QPushButton(Form)
        self.b.setMinimumSize(QtCore.QSize(0, 50))
        self.b.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.b.setObjectName("b")
        self.Keyboard_layout.addWidget(self.b, 3, 5, 1, 1)
        self.k_1 = QtWidgets.QPushButton(Form)
        self.k_1.setMinimumSize(QtCore.QSize(0, 50))
        self.k_1.setSizeIncrement(QtCore.QSize(0, 0))
        self.k_1.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.k_1.setObjectName("k_1")
        self.Keyboard_layout.addWidget(self.k_1, 0, 0, 1, 1)
        self.j = QtWidgets.QPushButton(Form)
        self.j.setMinimumSize(QtCore.QSize(0, 50))
        self.j.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.j.setObjectName("j")
        self.Keyboard_layout.addWidget(self.j, 2, 6, 1, 1)
        self.k_7 = QtWidgets.QPushButton(Form)
        self.k_7.setMinimumSize(QtCore.QSize(0, 50))
        self.k_7.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.k_7.setObjectName("k_7")
        self.Keyboard_layout.addWidget(self.k_7, 0, 6, 1, 1)
        self.o = QtWidgets.QPushButton(Form)
        self.o.setMinimumSize(QtCore.QSize(0, 50))
        self.o.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.o.setObjectName("o")
        self.Keyboard_layout.addWidget(self.o, 1, 8, 1, 1)
        self.q = QtWidgets.QPushButton(Form)
        self.q.setMinimumSize(QtCore.QSize(0, 50))
        self.q.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.q.setObjectName("q")
        self.Keyboard_layout.addWidget(self.q, 1, 0, 1, 1)
        self.x = QtWidgets.QPushButton(Form)
        self.x.setMinimumSize(QtCore.QSize(0, 50))
        self.x.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.x.setObjectName("x")
        self.Keyboard_layout.addWidget(self.x, 3, 2, 1, 1)
        self.s = QtWidgets.QPushButton(Form)
        self.s.setMinimumSize(QtCore.QSize(0, 50))
        self.s.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.s.setObjectName("s")
        self.Keyboard_layout.addWidget(self.s, 2, 1, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(Form)
        self.pushButton_28.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_28.setText("")
        self.pushButton_28.setFlat(True)
        self.pushButton_28.setObjectName("pushButton_28")
        self.Keyboard_layout.addWidget(self.pushButton_28, 2, 9, 1, 1)
        self.k_2 = QtWidgets.QPushButton(Form)
        self.k_2.setMinimumSize(QtCore.QSize(0, 50))
        self.k_2.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.k_2.setObjectName("k_2")
        self.Keyboard_layout.addWidget(self.k_2, 0, 1, 1, 1)
        self.u = QtWidgets.QPushButton(Form)
        self.u.setMinimumSize(QtCore.QSize(0, 50))
        self.u.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.u.setObjectName("u")
        self.Keyboard_layout.addWidget(self.u, 1, 6, 1, 1)
        self.e = QtWidgets.QPushButton(Form)
        self.e.setMinimumSize(QtCore.QSize(0, 50))
        self.e.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.e.setObjectName("e")
        self.Keyboard_layout.addWidget(self.e, 1, 2, 1, 1)
        self.k_4 = QtWidgets.QPushButton(Form)
        self.k_4.setMinimumSize(QtCore.QSize(0, 50))
        self.k_4.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.k_4.setObjectName("k_4")
        self.Keyboard_layout.addWidget(self.k_4, 0, 3, 1, 1)
        self.v = QtWidgets.QPushButton(Form)
        self.v.setMinimumSize(QtCore.QSize(0, 50))
        self.v.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.v.setObjectName("v")
        self.Keyboard_layout.addWidget(self.v, 3, 4, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(Form)
        self.pushButton_29.setText("")
        self.pushButton_29.setFlat(True)
        self.pushButton_29.setObjectName("pushButton_29")
        self.Keyboard_layout.addWidget(self.pushButton_29, 3, 9, 1, 1)
        self.k_0 = QtWidgets.QPushButton(Form)
        self.k_0.setMinimumSize(QtCore.QSize(0, 50))
        self.k_0.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.k_0.setObjectName("k_0")
        self.Keyboard_layout.addWidget(self.k_0, 0, 9, 1, 1)
        self.k_8 = QtWidgets.QPushButton(Form)
        self.k_8.setMinimumSize(QtCore.QSize(0, 50))
        self.k_8.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.k_8.setObjectName("k_8")
        self.Keyboard_layout.addWidget(self.k_8, 0, 7, 1, 1)
        self.r = QtWidgets.QPushButton(Form)
        self.r.setMinimumSize(QtCore.QSize(0, 50))
        self.r.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.r.setObjectName("r")
        self.Keyboard_layout.addWidget(self.r, 1, 3, 1, 1)
        self.y = QtWidgets.QPushButton(Form)
        self.y.setMinimumSize(QtCore.QSize(0, 50))
        self.y.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.y.setObjectName("y")
        self.Keyboard_layout.addWidget(self.y, 1, 5, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(Form)
        self.pushButton_21.setText("")
        self.pushButton_21.setFlat(True)
        self.pushButton_21.setObjectName("pushButton_21")
        self.Keyboard_layout.addWidget(self.pushButton_21, 3, 0, 1, 1)
        self.m = QtWidgets.QPushButton(Form)
        self.m.setMinimumSize(QtCore.QSize(0, 50))
        self.m.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.m.setObjectName("m")
        self.Keyboard_layout.addWidget(self.m, 3, 7, 1, 1)
        self.i = QtWidgets.QPushButton(Form)
        self.i.setMinimumSize(QtCore.QSize(0, 50))
        self.i.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.i.setObjectName("i")
        self.Keyboard_layout.addWidget(self.i, 1, 7, 1, 1)
        self.k_9 = QtWidgets.QPushButton(Form)
        self.k_9.setMinimumSize(QtCore.QSize(0, 50))
        self.k_9.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.k_9.setObjectName("k_9")
        self.Keyboard_layout.addWidget(self.k_9, 0, 8, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(Form)
        self.pushButton_30.setText("")
        self.pushButton_30.setFlat(True)
        self.pushButton_30.setObjectName("pushButton_30")
        self.Keyboard_layout.addWidget(self.pushButton_30, 1, 10, 1, 1)
        self.h = QtWidgets.QPushButton(Form)
        self.h.setMinimumSize(QtCore.QSize(0, 50))
        self.h.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.h.setObjectName("h")
        self.Keyboard_layout.addWidget(self.h, 2, 5, 1, 1)
        self.w = QtWidgets.QPushButton(Form)
        self.w.setMinimumSize(QtCore.QSize(0, 50))
        self.w.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.w.setObjectName("w")
        self.Keyboard_layout.addWidget(self.w, 1, 1, 1, 1)
        self.t = QtWidgets.QPushButton(Form)
        self.t.setMinimumSize(QtCore.QSize(0, 50))
        self.t.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.t.setObjectName("t")
        self.Keyboard_layout.addWidget(self.t, 1, 4, 1, 1)
        self.c = QtWidgets.QPushButton(Form)
        self.c.setMinimumSize(QtCore.QSize(0, 50))
        self.c.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.c.setObjectName("c")
        self.Keyboard_layout.addWidget(self.c, 3, 3, 1, 1)
        self.k = QtWidgets.QPushButton(Form)
        self.k.setMinimumSize(QtCore.QSize(0, 50))
        self.k.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.k.setObjectName("k")
        self.Keyboard_layout.addWidget(self.k, 2, 7, 1, 1)
        self.hide = QtWidgets.QPushButton(Form)
        self.hide.setMinimumSize(QtCore.QSize(0, 60))
        self.hide.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.hide.setObjectName("hide")
        self.Keyboard_layout.addWidget(self.hide, 3, 10, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_8.setText("")
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.Keyboard_layout.addWidget(self.pushButton_8, 3, 8, 1, 1)
        self.k_5 = QtWidgets.QPushButton(Form)
        self.k_5.setMinimumSize(QtCore.QSize(0, 50))
        self.k_5.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.k_5.setObjectName("k_5")
        self.Keyboard_layout.addWidget(self.k_5, 0, 4, 1, 1)
        self.d = QtWidgets.QPushButton(Form)
        self.d.setMinimumSize(QtCore.QSize(0, 50))
        self.d.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.d.setObjectName("d")
        self.Keyboard_layout.addWidget(self.d, 2, 2, 1, 1)
        self.l = QtWidgets.QPushButton(Form)
        self.l.setMinimumSize(QtCore.QSize(0, 50))
        self.l.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.l.setObjectName("l")
        self.Keyboard_layout.addWidget(self.l, 2, 8, 1, 1)
        self.g = QtWidgets.QPushButton(Form)
        self.g.setMinimumSize(QtCore.QSize(0, 50))
        self.g.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.g.setObjectName("g")
        self.Keyboard_layout.addWidget(self.g, 2, 4, 1, 1)
        self.f = QtWidgets.QPushButton(Form)
        self.f.setMinimumSize(QtCore.QSize(0, 50))
        self.f.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.f.setObjectName("f")
        self.Keyboard_layout.addWidget(self.f, 2, 3, 1, 1)
        self.k_6 = QtWidgets.QPushButton(Form)
        self.k_6.setMinimumSize(QtCore.QSize(0, 50))
        self.k_6.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.k_6.setObjectName("k_6")
        self.Keyboard_layout.addWidget(self.k_6, 0, 5, 1, 1)
        self.n = QtWidgets.QPushButton(Form)
        self.n.setMinimumSize(QtCore.QSize(0, 50))
        self.n.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.n.setObjectName("n")
        self.Keyboard_layout.addWidget(self.n, 3, 6, 1, 1)
        self.backspace = QtWidgets.QPushButton(Form)
        self.backspace.setMinimumSize(QtCore.QSize(0, 50))
        self.backspace.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.backspace.setObjectName("backspace")
        self.Keyboard_layout.addWidget(self.backspace, 0, 10, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(Form)
        self.pushButton_32.setText("")
        self.pushButton_32.setFlat(True)
        self.pushButton_32.setObjectName("pushButton_32")
        self.Keyboard_layout.addWidget(self.pushButton_32, 2, 10, 1, 1)
        self.z = QtWidgets.QPushButton(Form)
        self.z.setMinimumSize(QtCore.QSize(0, 50))
        self.z.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.z.setObjectName("z")
        self.Keyboard_layout.addWidget(self.z, 3, 1, 1, 1)
        self.k_3 = QtWidgets.QPushButton(Form)
        self.k_3.setMinimumSize(QtCore.QSize(0, 50))
        self.k_3.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.k_3.setObjectName("k_3")
        self.Keyboard_layout.addWidget(self.k_3, 0, 2, 1, 1)
        self.p = QtWidgets.QPushButton(Form)
        self.p.setMinimumSize(QtCore.QSize(0, 50))
        self.p.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.p.setObjectName("p")
        self.Keyboard_layout.addWidget(self.p, 1, 9, 1, 1)
        self.a = QtWidgets.QPushButton(Form)
        self.a.setMinimumSize(QtCore.QSize(0, 50))
        self.a.setStyleSheet("QPushButton { background-color: rgba(255, 255, 255, 255);\n"
"font: 12pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"font: 12pt \"Ubuntu\";\n"
"color:black;\n"
"border: 0px; }")
        self.a.setObjectName("a")
        self.Keyboard_layout.addWidget(self.a, 2, 0, 1, 1)
        self.Main_layout.addLayout(self.Keyboard_layout, 5, 0, 1, 1)
        self.Setting_button_layout = QtWidgets.QHBoxLayout()
        self.Setting_button_layout.setObjectName("Setting_button_layout")
        self.Setting_button = QtWidgets.QPushButton(Form)
        self.Setting_button.setObjectName("Setting_button")
        self.Setting_button_layout.addWidget(self.Setting_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Setting_button_layout.addItem(spacerItem)
        self.Main_layout.addLayout(self.Setting_button_layout, 0, 0, 1, 1)
        self.Call_buttons_layout = QtWidgets.QHBoxLayout()
        self.Call_buttons_layout.setContentsMargins(0, 0, -1, -1)
        self.Call_buttons_layout.setObjectName("Call_buttons_layout")
        self.Answer_button = QtWidgets.QPushButton(Form)
        self.Answer_button.setMinimumSize(QtCore.QSize(0, 60))
        self.Answer_button.setStyleSheet("QPushButton { \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(38, 162, 105);\n"
"font: 14pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"color:black;\n"
"border: 0px; }")
        self.Answer_button.setObjectName("Answer_button")
        self.Call_buttons_layout.addWidget(self.Answer_button)
        self.Call_button = QtWidgets.QPushButton(Form)
        self.Call_button.setMinimumSize(QtCore.QSize(0, 60))
        self.Call_button.setStyleSheet("QPushButton { \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(26, 95, 180);\n"
"font: 14pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"color:black;\n"
"border: 0px; }")
        self.Call_button.setObjectName("Call_button")
        self.Call_buttons_layout.addWidget(self.Call_button)
        self.Decline_button = QtWidgets.QPushButton(Form)
        self.Decline_button.setMinimumSize(QtCore.QSize(0, 60))
        self.Decline_button.setStyleSheet("QPushButton { \n"
"    background-color: rgb(246, 97, 81);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"font: 15pt \"Ubuntu\";\n"
"border: 1px;\n"
"border-radius: 5px}\n"
"QPushButton:focuspressed {background-color: rgba(255, 255, 255, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"color:black;\n"
"border: 0px; }\n"
" QPushButton:pressed {background-color: rgba(150, 150, 150, 255);\n"
"gridline-color: rgb(198, 70, 0);\n"
"color:black;\n"
"border: 0px; }")
        self.Decline_button.setObjectName("Decline_button")
        self.Call_buttons_layout.addWidget(self.Decline_button)
        self.Main_layout.addLayout(self.Call_buttons_layout, 6, 0, 1, 1)
        self.Search_text = QtWidgets.QHBoxLayout()
        self.Search_text.setContentsMargins(-1, 0, -1, -1)
        self.Search_text.setObjectName("Search_text")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Search_text.addItem(spacerItem1)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setStyleSheet("font: 15pt \"Ubuntu\";")
        self.lineEdit.setObjectName("lineEdit")
        self.Search_text.addWidget(self.lineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Search_text.addItem(spacerItem2)
        self.Main_layout.addLayout(self.Search_text, 4, 0, 1, 1)
        self.Lista_recent_layout = QtWidgets.QHBoxLayout()
        self.Lista_recent_layout.setObjectName("Lista_recent_layout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Lista_recent_layout.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.listView = QtWidgets.QListView(Form)
        self.listView.setMinimumSize(QtCore.QSize(0, 200))
        self.listView.setMaximumSize(QtCore.QSize(16777215, 200))
        self.listView.setStyleSheet("background-color: transparent;\n"
"font: 15pt \"Ubuntu\";\n"
"border: 0px;")
        self.listView.setObjectName("listView")
        self.horizontalLayout_3.addWidget(self.listView)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.Lista_recent_layout.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Lista_recent_layout.addItem(spacerItem6)
        self.Main_layout.addLayout(self.Lista_recent_layout, 1, 0, 1, 1)
        self.chujechuje = QtWidgets.QLabel(Form)
        self.chujechuje.setStyleSheet("color: rgb(255, 255, 255);")
        self.chujechuje.setObjectName("chujechuje")
        self.Main_layout.addWidget(self.chujechuje, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.Main_layout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Status_button.setText(_translate("Form", "Status"))
        self.Recent_button.setText(_translate("Form", "Recent"))
        self.Contacts_button.setText(_translate("Form", "Contacts"))
        self.b.setText(_translate("Form", "b"))
        self.k_1.setText(_translate("Form", "1"))
        self.j.setText(_translate("Form", "j"))
        self.k_7.setText(_translate("Form", "7"))
        self.o.setText(_translate("Form", "o"))
        self.q.setText(_translate("Form", "q"))
        self.x.setText(_translate("Form", "x"))
        self.s.setText(_translate("Form", "s"))
        self.k_2.setText(_translate("Form", "2"))
        self.u.setText(_translate("Form", "u"))
        self.e.setText(_translate("Form", "e"))
        self.k_4.setText(_translate("Form", "4"))
        self.v.setText(_translate("Form", "v"))
        self.k_0.setText(_translate("Form", "0"))
        self.k_8.setText(_translate("Form", "8"))
        self.r.setText(_translate("Form", "r"))
        self.y.setText(_translate("Form", "y"))
        self.m.setText(_translate("Form", "m"))
        self.i.setText(_translate("Form", "i"))
        self.k_9.setText(_translate("Form", "9"))
        self.h.setText(_translate("Form", "h"))
        self.w.setText(_translate("Form", "w"))
        self.t.setText(_translate("Form", "t"))
        self.c.setText(_translate("Form", "c"))
        self.k.setText(_translate("Form", "k"))
        self.hide.setText(_translate("Form", "Hide"))
        self.k_5.setText(_translate("Form", "5"))
        self.d.setText(_translate("Form", "d"))
        self.l.setText(_translate("Form", "l"))
        self.g.setText(_translate("Form", "g"))
        self.f.setText(_translate("Form", "f"))
        self.k_6.setText(_translate("Form", "6"))
        self.n.setText(_translate("Form", "n"))
        self.backspace.setText(_translate("Form", "<"))
        self.z.setText(_translate("Form", "z"))
        self.k_3.setText(_translate("Form", "3"))
        self.p.setText(_translate("Form", "p"))
        self.a.setText(_translate("Form", "a"))
        self.Setting_button.setText(_translate("Form", "PushButton"))
        self.Answer_button.setText(_translate("Form", "Answer"))
        self.Call_button.setText(_translate("Form", "Call"))
        self.Decline_button.setText(_translate("Form", "Decline"))
        self.chujechuje.setText(_translate("Form", "TextLabel"))
